"""Split conformal prediction that stays valid under covariate shift.

Standard split conformal guarantees :math:`P(Y \\in C(X)) \\ge 1-\\alpha` only when the
calibration and test points are exchangeable. Perturbing the test inputs -- which is the
whole point of a pre-deployment stress test -- breaks exchangeability, so the guarantee the
unweighted method advertises no longer applies to the regime being tested.

Tibshirani, Barber, Candes and Ramdas (2019), "Conformal prediction under covariate shift",
restore validity when the shift is a pure covariate shift

    P_test(x, y) = w(x) P_cal(x, y),      w(x) = dP_test(x) / dP_cal(x),

by replacing the empirical quantile of the calibration scores with a *weighted* quantile in
which calibration point *i* carries mass

    p_i(x) = w(x_i) / (sum_j w(x_j) + w(x)),

plus an atom of mass w(x) / (sum_j w(x_j) + w(x)) at +infinity. The resulting set satisfies
P(Y in C(X)) >= 1-alpha under the shifted distribution, for any w known up to a constant.

Two weight sources are supported, and the distinction matters for how a result should be read:

``oracle``
    The shift was generated by tilted sampling with a known tilt t(x), so w(x) ∝ t(x) is exact.
    This is the only setting in which the theorem's premise holds exactly, and it is available
    here because the cohort is simulated.

``estimated``
    The shift is an arbitrary perturbation (noise, masking, degradation) with no closed-form
    density ratio. The ratio is estimated by probabilistic classification: a discriminator is
    trained to separate calibration from test covariates and

        w(x) = [d(x) / (1 - d(x))] * (n_cal / n_test),

    the standard density-ratio-by-classification estimator. Coverage is then only as good as
    the ratio estimate, which this module does not hide: ``weighted_conformal_coverage``
    reports the achieved coverage for both weightings so the gap is visible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_predict

__all__ = [
    "WeightedConformalResult",
    "weighted_quantile",
    "estimate_density_ratio",
    "weighted_split_conformal",
]


@dataclass
class WeightedConformalResult:
    """Outcome of one weighted split-conformal run."""

    alpha: float
    coverage: float
    avg_set_size: float
    weighting: str
    n_cal: int
    n_test: int
    qhat_mean: float
    covered: np.ndarray = field(repr=False)
    set_sizes: np.ndarray = field(repr=False)

    def as_row(self, **extra) -> dict:
        row = {
            "weighting": self.weighting,
            "alpha": self.alpha,
            "coverage": self.coverage,
            "avg_set_size": self.avg_set_size,
            "n_cal": self.n_cal,
            "n_test": self.n_test,
            "qhat_mean": self.qhat_mean,
        }
        row.update(extra)
        return row


def weighted_quantile(scores: np.ndarray, weights: np.ndarray, level: float,
                      test_weight: float) -> float:
    """Weighted (1-alpha) quantile of calibration scores with the +infinity atom.

    ``level`` is 1-alpha. Following Tibshirani et al. (2019, Eq. 5) the test point's own
    weight forms an atom at +infinity; when it carries enough mass the quantile is infinite
    and the prediction set is the whole label space -- the honest answer when the shift puts
    the test point where there is no calibration data.
    """
    scores = np.asarray(scores, dtype=float)
    weights = np.asarray(weights, dtype=float)
    order = np.argsort(scores)
    scores, weights = scores[order], weights[order]

    total = weights.sum() + test_weight
    if total <= 0:
        return float("inf")
    cum = np.cumsum(weights) / total
    idx = np.searchsorted(cum, level, side="left")
    if idx >= len(scores):
        return float("inf")  # the atom at +infinity carries the remaining mass
    return float(scores[idx])


def estimate_density_ratio(X_cal: np.ndarray, X_test: np.ndarray, seed: int = 42,
                           clip: tuple[float, float] = (1e-3, 1e3)
                           ) -> tuple[np.ndarray, np.ndarray]:
    """Density ratio dP_test/dP_cal, returned for the calibration AND the test points.

    Both sets need weights: the calibration points carry the quantile's mass and the test
    point carries the atom at +infinity. Cross-fitted out-of-fold probabilities are used
    throughout so no point is weighted by a discriminator that has seen it in training.
    """
    X = np.vstack([np.asarray(X_cal, dtype=float), np.asarray(X_test, dtype=float)])
    z = np.concatenate([np.zeros(len(X_cal)), np.ones(len(X_test))])
    clf = GradientBoostingClassifier(random_state=seed)
    prob = cross_val_predict(clf, X, z, cv=5, method="predict_proba")[:, 1]
    prob = np.clip(prob, 1e-6, 1 - 1e-6)
    ratio = (prob / (1.0 - prob)) * (len(X_cal) / max(len(X_test), 1))
    ratio = np.clip(ratio, *clip)
    return ratio[: len(X_cal)], ratio[len(X_cal):]


def weighted_split_conformal(model, X_cal: np.ndarray, y_cal: np.ndarray,
                             X_test: np.ndarray, y_test: np.ndarray,
                             alpha: float = 0.10,
                             weights_cal: Optional[np.ndarray] = None,
                             weights_test: Optional[np.ndarray] = None,
                             weighting: str = "unweighted") -> WeightedConformalResult:
    """Split conformal sets with optional covariate-shift weights.

    Nonconformity score is 1 - p_model(y | x), the standard choice for classification.
    ``weights_cal``/``weights_test`` are the density ratios w(x); passing None reproduces
    ordinary split conformal, which is what makes the two arms directly comparable.
    """
    proba_cal = model.predict_proba(X_cal)
    proba_test = model.predict_proba(X_test)
    classes = np.asarray(model.classes_)

    cal_idx = np.array([np.where(classes == yi)[0][0] for yi in y_cal])
    scores = 1.0 - proba_cal[np.arange(len(y_cal)), cal_idx]

    if weights_cal is None:
        weights_cal = np.ones(len(y_cal))
    if weights_test is None:
        weights_test = np.ones(len(y_test))

    level = 1.0 - alpha
    covered, sizes, qhats = [], [], []
    for i in range(len(y_test)):
        qhat = weighted_quantile(scores, weights_cal, level, float(weights_test[i]))
        qhats.append(qhat)
        member = (1.0 - proba_test[i]) <= qhat
        sizes.append(int(member.sum()))
        true_pos = np.where(classes == y_test[i])[0][0]
        covered.append(bool(member[true_pos]))

    covered = np.asarray(covered)
    sizes = np.asarray(sizes)
    finite = [q for q in qhats if np.isfinite(q)]
    return WeightedConformalResult(
        alpha=alpha,
        coverage=float(covered.mean()),
        avg_set_size=float(sizes.mean()),
        weighting=weighting,
        n_cal=len(y_cal),
        n_test=len(y_test),
        qhat_mean=float(np.mean(finite)) if finite else float("inf"),
        covered=covered,
        set_sizes=sizes,
    )
